const fs = require('fs');
const path = require('path');
const frontendRoot = path.resolve(__dirname, '..', '..', 'frontend');
const file = path.resolve(__dirname, '..', '..', 'frontend', 'about', 'index.html');
const route = path.relative(frontendRoot, path.dirname(file)).replace(/\\/g, '/');
const pageFile = route === '' ? path.join(path.resolve(__dirname, '..', 'src', 'app'), 'page.jsx') : path.join(path.resolve(__dirname, '..', 'src', 'app'), route, 'page.jsx');
const txt = fs.readFileSync(file, 'utf8');
const parseTag = (text, tag) => {
  const regex = new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`, 'i');
  const m = text.match(regex);
  return m ? m[1].trim() : '';
};
const parseMeta = (text, attr, value) => {
  const needle = `<meta ${attr}="${value}" content="`;
  const idx = text.indexOf(needle);
  if (idx === -1) return '';
  const start = idx + needle.length;
  const end = text.indexOf('"', start);
  return end === -1 ? '' : text.slice(start, end).trim();
};
const title = parseTag(txt, 'title');
const description = parseMeta(txt, 'name', 'description');
console.log({ route, pageFile, title });
  lines.push('  authors: [{ name: "Innovation Dynamics Group LLC" }],');
  lines.push(`  alternates: { canonical: ${JSON.stringify(metadata.alternates.canonical)} },`);
  lines.push('  openGraph: {');
  lines.push(`    title: ${JSON.stringify(metadata.openGraph.title)},`);
  lines.push(`    description: ${JSON.stringify(metadata.openGraph.description)},`);
  lines.push(`    url: ${JSON.stringify(metadata.openGraph.url)},`);
  lines.push('    siteName: "Innovation Dynamics Group",');
  lines.push('    type: "website",');
  lines.push('    locale: "en_US",');
  lines.push('    images: [');
  lines.push('      {');
  lines.push(`        url: ${JSON.stringify(metadata.openGraph.images[0].url)},`);
  lines.push('        width: 1200,');
  lines.push('        height: 630,');
  lines.push(`        alt: ${JSON.stringify(metadata.openGraph.images[0].alt)},`);
  lines.push('      },');
  lines.push('    ],');
  lines.push('  },');
  lines.push('  twitter: {');
  lines.push('    card: "summary_large_image",');
  lines.push(`    title: ${JSON.stringify(metadata.twitter.title)},`);
  lines.push(`    description: ${JSON.stringify(metadata.twitter.description)},`);
  lines.push('    images: [');
  lines.push(`      ${JSON.stringify(metadata.twitter.images[0])},`);
  lines.push('    ],');
  lines.push('  },');
  lines.push('};');
  return lines.join('\n');
};
console.log(formatMetadata(metadata));
